# Generated by Django 3.0.7 on 2020-07-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200629_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
